### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by drno-reg** [dazheng/gohive#4]
Hello, did try to use your lib,
process compile did stop and did return error:

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x5ee0ad]

goroutine 1 [running]:
github.com/dazheng/gohive.(*Connection).isOpen(...)
	C:/Go/dev/src/github.com/dazheng/gohive/connection.go:97
github.com/dazheng/gohive.(*Connection).Close(0x0, 0x10, 0xc042077f58)
	C:/Go/dev/src/github.com/dazheng/gohive/connection.go:103 +0x2d
main.main()
	C:/Servers/Repository/Projects/um_open/templates/Test/hive2.go:32 +0x145

Please, help to solve problem.

**Comment by dazheng** [comment]
did you use “go getgithub.com/dazheng/gohive”?

**Comment by arjun-ajith-gl** [comment]
hi @dazheng I am also getting this panic. I did "go get github.com/dazheng/gohive"

**Comment by likemezhoujie** [comment]
hi~ @dazheng I am also getting this panic. I did "go get github.com/dazheng/gohive" too,please help to solve the problem.

**Comment by SandyLQ** [comment]
Hello, I am also getting this panic, I imported the "github.com/dazheng/gohive", can you please check it out

**Comment by zalmanzhao** [comment]
hi~ @dazheng  I am also getting this panic. I did "go get github.com/dazheng/gohive" too,please help to solve the problem.
